In [7]:
import pandas as pd
import numpy as np

In [8]:
df = pd.read_csv('Data/Melbourne01.csv', on_bad_lines = "skip", low_memory=False)
df

,2011,1,1.1,0,4,24.8,0.0,14.0,51,SE,11,13,1007.4,0.0.1
0,2011,1,1.0,0.0,4.0,24.8,0.0,14.0,51.0,SE,11.0,13.0,1007.4,0.0
1,2011,1,1.0,0.0,14.0,24.8,0.0,13.3,48.0,SE,11.0,11.0,1007.5,0.0
2,2011,1,1.0,0.0,14.0,24.8,0.0,13.3,48.0,SE,11.0,11.0,1007.5,0.0
3,2011,1,1.0,0.0,24.0,24.9,0.0,13.3,48.0,SE,11.0,13.0,1007.5,0.0
4,2011,1,1.0,0.0,24.0,24.9,0.0,13.3,48.0,SE,11.0,13.0,1007.5,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1113146,2025,03,12.0,15.0,30.0,33.4,32.5,14.9,32.0,NW,20.0,35.0,1014.6,0.0
1113147,2025,03,12.0,15.0,34.0,33.5,32.9,14.5,31.0,NNW,26.0,41.0,1014.6,0.0
1113148,2025,03,12.0,16.0,0.0,34.4,34.2,14.8,30.0,WNW,26.0,41.0,1014.4,0.0
1113149,2025,03,12.0,16.0,30.0,33.6,32.4,14.1,30.0,WNW,26.0,41.0,1014.1,0.0
1113150,2025,03,12.0,16.0,30.0,33.6,32.4,14.1,30.0,NW,28.0,35.0,1014.1,0.0

In [9]:
# New list of column names
new_names = ['year', 'month', 'day', 'hour', 'minute', 'Air Temp (degrees C)', 'Apparent Temp (degrees C)', 'Dew Pt Temp (degrees C)',
            'Humidity (%)', 'Wind Direction', 'Wind Speed (km/h)', 'Wind Gust (km/h)', 'MSLP (hPa)', 'Rainfall since 9 am (mm)']

# Assign the new names
df.columns = new_names
df.head()

,year,month,day,hour,minute,Air Temp (degrees C),Apparent Temp (degrees C),Dew Pt Temp (degrees C),Humidity (%),Wind Direction,Wind Speed (km/h),Wind Gust (km/h),MSLP (hPa),Rainfall since 9 am (mm)
0,2011,1,1.0,0.0,4.0,24.8,0.0,14.0,51.0,SE,11.0,13.0,1007.4,0.0
1,2011,1,1.0,0.0,14.0,24.8,0.0,13.3,48.0,SE,11.0,11.0,1007.5,0.0
2,2011,1,1.0,0.0,14.0,24.8,0.0,13.3,48.0,SE,11.0,11.0,1007.5,0.0
3,2011,1,1.0,0.0,24.0,24.9,0.0,13.3,48.0,SE,11.0,13.0,1007.5,0.0
4,2011,1,1.0,0.0,24.0,24.9,0.0,13.3,48.0,SE,11.0,13.0,1007.5,0.0

In [10]:
df.describe()

,day,hour,minute,Air Temp (degrees C),Apparent Temp (degrees C),Dew Pt Temp (degrees C),Humidity (%),Wind Speed (km/h),Wind Gust (km/h),MSLP (hPa)
count,1.112519e+06,1.112519e+06,1.112519e+06,1.112519e+06,1.112519e+06,1.112519e+06,1.112519e+06,1.112519e+06,1.112519e+06,1.112519e+06
mean,1.576249e+01,1.143810e+01,2.612173e+01,1.577824e+01,1.204983e+01,9.005480e+00,6.695097e+01,1.927091e+01,2.250276e+01,1.016938e+03
std,8.809833e+00,6.886433e+00,1.724269e+01,5.614749e+00,1.517625e+01,4.061581e+00,1.766610e+01,2.556251e+01,3.398165e+01,6.181442e+01
min,1.000000e+00,0.000000e+00,0.000000e+00,5.000000e-01,-9.999000e+03,-9.600000e+00,0.000000e+00,-9.999000e+03,-9.999000e+03,-9.999000e+03
25%,8.000000e+00,5.000000e+00,1.000000e+01,1.180000e+01,7.600000e+00,6.000000e+00,5.500000e+01,1.100000e+01,1.300000e+01,1.012300e+03
50%,1.600000e+01,1.100000e+01,3.000000e+01,1.510000e+01,1.170000e+01,8.500000e+00,6.800000e+01,1.700000e+01,2.000000e+01,1.017400e+03
75%,2.300000e+01,1.700000e+01,4.000000e+01,1.890000e+01,1.650000e+01,1.160000e+01,8.000000e+01,2.600000e+01,3.000000e+01,1.022600e+03
max,3.100000e+01,2.300000e+01,5.900000e+01,4.350000e+01,4.330000e+01,3.690000e+01,1.000000e+02,1.000000e+02,1.090000e+02,1.041900e+03

## Deal with Shifted Columns

combine fixed shifted_column dataframe with the normal (but not complete) dataframe

In [11]:
shifted_df = pd.read_csv('Data/Melbourne01-fixxing.csv', low_memory = False)
shifted_df

,2011,1,1.1,0,4,24.8,0.1,14,51,SE,11,13,1007.4,0.2
0,2011,1,1.0,0.0,4.0,24.8,0.0,14.0,51.0,SE,11.0,13.0,1007.4,0
1,2011,1,1.0,0.0,14.0,24.8,0.0,13.3,48.0,SE,11.0,11.0,1007.5,0
2,2011,1,1.0,0.0,14.0,24.8,0.0,13.3,48.0,SE,11.0,11.0,1007.5,0
3,2011,1,1.0,0.0,24.0,24.9,0.0,13.3,48.0,SE,11.0,13.0,1007.5,0
4,2011,1,1.0,0.0,24.0,24.9,0.0,13.3,48.0,SE,11.0,13.0,1007.5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,2022,6,28.0,16.0,40.0,12.1,7.9,3.9,57.0,N,24.0,28.0,1027.0,0
1048571,2022,6,28.0,16.0,40.0,12.1,7.9,3.9,57.0,N,24.0,28.0,1027.0,0
1048572,2022,6,28.0,16.0,50.0,11.9,8.5,3.9,58.0,N,19.0,20.0,1027.1,0
1048573,2022,6,28.0,16.0,50.0,11.9,8.5,3.9,58.0,N,19.0,20.0,1027.1,0
1048574,2022,6,28.0,17.0,0.0,11.9,7.7,3.9,58.0,N,24.0,28.0,1027.2,0

In [12]:
shifted_df.columns = new_names
shifted_df.head()

,year,month,day,hour,minute,Air Temp (degrees C),Apparent Temp (degrees C),Dew Pt Temp (degrees C),Humidity (%),Wind Direction,Wind Speed (km/h),Wind Gust (km/h),MSLP (hPa),Rainfall since 9 am (mm)
0,2011,1,1.0,0.0,4.0,24.8,0.0,14.0,51.0,SE,11.0,13.0,1007.4,0
1,2011,1,1.0,0.0,14.0,24.8,0.0,13.3,48.0,SE,11.0,11.0,1007.5,0
2,2011,1,1.0,0.0,14.0,24.8,0.0,13.3,48.0,SE,11.0,11.0,1007.5,0
3,2011,1,1.0,0.0,24.0,24.9,0.0,13.3,48.0,SE,11.0,13.0,1007.5,0
4,2011,1,1.0,0.0,24.0,24.9,0.0,13.3,48.0,SE,11.0,13.0,1007.5,0

In [13]:
all_df = pd.concat([df,shifted_df], join='outer')
all_df = all_df.sort_index()
all_df

,year,month,day,hour,minute,Air Temp (degrees C),Apparent Temp (degrees C),Dew Pt Temp (degrees C),Humidity (%),Wind Direction,Wind Speed (km/h),Wind Gust (km/h),MSLP (hPa),Rainfall since 9 am (mm)
0,2011,1,1.0,0.0,4.0,24.8,0.0,14.0,51.0,SE,11.0,13.0,1007.4,0.0
0,2011,1,1.0,0.0,4.0,24.8,0.0,14.0,51.0,SE,11.0,13.0,1007.4,0
1,2011,1,1.0,0.0,14.0,24.8,0.0,13.3,48.0,SE,11.0,11.0,1007.5,0
1,2011,1,1.0,0.0,14.0,24.8,0.0,13.3,48.0,SE,11.0,11.0,1007.5,0.0
2,2011,1,1.0,0.0,14.0,24.8,0.0,13.3,48.0,SE,11.0,11.0,1007.5,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1113146,2025,03,12.0,15.0,30.0,33.4,32.5,14.9,32.0,NW,20.0,35.0,1014.6,0.0
1113147,2025,03,12.0,15.0,34.0,33.5,32.9,14.5,31.0,NNW,26.0,41.0,1014.6,0.0
1113148,2025,03,12.0,16.0,0.0,34.4,34.2,14.8,30.0,WNW,26.0,41.0,1014.4,0.0
1113149,2025,03,12.0,16.0,30.0,33.6,32.4,14.1,30.0,WNW,26.0,41.0,1014.1,0.0
1113150,2025,03,12.0,16.0,30.0,33.6,32.4,14.1,30.0,NW,28.0,35.0,1014.1,0.0

## Deal with Duplicated Rows

In [14]:
# all_df['day'] = pd.to_numeric(all_df['day'], errors='coerce')
# all_df['hour'] = pd.to_numeric(all_df['hour'], errors='coerce')
# all_df['minute'] = pd.to_numeric(all_df['minute'], errors='coerce')
all_df['Air Temp (degrees C)'] = pd.to_numeric(all_df['Air Temp (degrees C)'], errors='coerce')
all_df['Apparent Temp (degrees C)'] = pd.to_numeric(all_df['Apparent Temp (degrees C)'], errors='coerce')
all_df['Dew Pt Temp (degrees C)'] = pd.to_numeric(all_df['Dew Pt Temp (degrees C)'], errors='coerce')
all_df['Humidity (%)'] = pd.to_numeric(all_df['Humidity (%)'], errors='coerce')
# all_df['Wind Direction'] = all_df['Wind Direction'].astype(str)
# df['Wind Direction'] = df['Wind Direction'].str.strip()
all_df['Wind Speed (km/h)'] = pd.to_numeric(all_df['Wind Speed (km/h)'], errors='coerce')
all_df['Wind Gust (km/h)'] = pd.to_numeric(all_df['Wind Gust (km/h)'], errors='coerce')
all_df['MSLP (hPa)'] = pd.to_numeric(all_df['MSLP (hPa)'], errors='coerce')
all_df['Rainfall since 9 am (mm)'] = pd.to_numeric(all_df['Rainfall since 9 am (mm)'], errors='coerce')
all_df['Rainfall since 9 am (mm)'] = all_df['Rainfall since 9 am (mm)'].fillna(0)
all_df

,year,month,day,hour,minute,Air Temp (degrees C),Apparent Temp (degrees C),Dew Pt Temp (degrees C),Humidity (%),Wind Direction,Wind Speed (km/h),Wind Gust (km/h),MSLP (hPa),Rainfall since 9 am (mm)
0,2011,1,1.0,0.0,4.0,24.8,0.0,14.0,51.0,SE,11.0,13.0,1007.4,0.0
0,2011,1,1.0,0.0,4.0,24.8,0.0,14.0,51.0,SE,11.0,13.0,1007.4,0.0
1,2011,1,1.0,0.0,14.0,24.8,0.0,13.3,48.0,SE,11.0,11.0,1007.5,0.0
1,2011,1,1.0,0.0,14.0,24.8,0.0,13.3,48.0,SE,11.0,11.0,1007.5,0.0
2,2011,1,1.0,0.0,14.0,24.8,0.0,13.3,48.0,SE,11.0,11.0,1007.5,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1113146,2025,03,12.0,15.0,30.0,33.4,32.5,14.9,32.0,NW,20.0,35.0,1014.6,0.0
1113147,2025,03,12.0,15.0,34.0,33.5,32.9,14.5,31.0,NNW,26.0,41.0,1014.6,0.0
1113148,2025,03,12.0,16.0,0.0,34.4,34.2,14.8,30.0,WNW,26.0,41.0,1014.4,0.0
1113149,2025,03,12.0,16.0,30.0,33.6,32.4,14.1,30.0,WNW,26.0,41.0,1014.1,0.0
1113150,2025,03,12.0,16.0,30.0,33.6,32.4,14.1,30.0,NW,28.0,35.0,1014.1,0.0

In [15]:
print(all_df.duplicated().sum())

1075766

In [16]:
all_df_fixed = all_df.drop_duplicates()
all_df_fixed = all_df_fixed.reset_index(drop=True)
all_df_fixed

,year,month,day,hour,minute,Air Temp (degrees C),Apparent Temp (degrees C),Dew Pt Temp (degrees C),Humidity (%),Wind Direction,Wind Speed (km/h),Wind Gust (km/h),MSLP (hPa),Rainfall since 9 am (mm)
0,2011,1,1.0,0.0,4.0,24.8,0.0,14.0,51.0,SE,11.0,13.0,1007.4,0.0
1,2011,1,1.0,0.0,4.0,24.8,0.0,14.0,51.0,SE,11.0,13.0,1007.4,0.0
2,2011,1,1.0,0.0,14.0,24.8,0.0,13.3,48.0,SE,11.0,11.0,1007.5,0.0
3,2011,1,1.0,0.0,14.0,24.8,0.0,13.3,48.0,SE,11.0,11.0,1007.5,0.0
4,2011,1,1.0,0.0,24.0,24.9,0.0,13.3,48.0,SE,11.0,13.0,1007.5,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1085955,2025,03,12.0,15.0,30.0,33.4,32.5,14.9,32.0,NW,20.0,35.0,1014.6,0.0
1085956,2025,03,12.0,15.0,34.0,33.5,32.9,14.5,31.0,NNW,26.0,41.0,1014.6,0.0
1085957,2025,03,12.0,16.0,0.0,34.4,34.2,14.8,30.0,WNW,26.0,41.0,1014.4,0.0
1085958,2025,03,12.0,16.0,30.0,33.6,32.4,14.1,30.0,WNW,26.0,41.0,1014.1,0.0
1085959,2025,03,12.0,16.0,30.0,33.6,32.4,14.1,30.0,NW,28.0,35.0,1014.1,0.0

## Deal with clustered rows

In [17]:
print(all_df_fixed.isna().sum())

year                           0
month                        616
day                          632
hour                         632
minute                       632
Air Temp (degrees C)         632
Apparent Temp (degrees C)    632
Dew Pt Temp (degrees C)      632
Humidity (%)                 632
Wind Direction               632
Wind Speed (km/h)            632
Wind Gust (km/h)             632
MSLP (hPa)                   632
Rainfall since 9 am (mm)       0
dtype: int64

In [18]:
need_fix_rows = np.where(all_df_fixed['day'].isna())[0].tolist()
# print(need_fix_rows)
print(len(need_fix_rows))

632

In [19]:
good_rows = all_df_fixed.index.difference(need_fix_rows)
len(good_rows)

1085328

### Good Rows DF

In [20]:
good_df = all_df_fixed.loc[good_rows]
good_df

,year,month,day,hour,minute,Air Temp (degrees C),Apparent Temp (degrees C),Dew Pt Temp (degrees C),Humidity (%),Wind Direction,Wind Speed (km/h),Wind Gust (km/h),MSLP (hPa),Rainfall since 9 am (mm)
0,2011,1,1.0,0.0,4.0,24.8,0.0,14.0,51.0,SE,11.0,13.0,1007.4,0.0
1,2011,1,1.0,0.0,4.0,24.8,0.0,14.0,51.0,SE,11.0,13.0,1007.4,0.0
2,2011,1,1.0,0.0,14.0,24.8,0.0,13.3,48.0,SE,11.0,11.0,1007.5,0.0
3,2011,1,1.0,0.0,14.0,24.8,0.0,13.3,48.0,SE,11.0,11.0,1007.5,0.0
4,2011,1,1.0,0.0,24.0,24.9,0.0,13.3,48.0,SE,11.0,13.0,1007.5,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1085955,2025,03,12.0,15.0,30.0,33.4,32.5,14.9,32.0,NW,20.0,35.0,1014.6,0.0
1085956,2025,03,12.0,15.0,34.0,33.5,32.9,14.5,31.0,NNW,26.0,41.0,1014.6,0.0
1085957,2025,03,12.0,16.0,0.0,34.4,34.2,14.8,30.0,WNW,26.0,41.0,1014.4,0.0
1085958,2025,03,12.0,16.0,30.0,33.6,32.4,14.1,30.0,WNW,26.0,41.0,1014.1,0.0
1085959,2025,03,12.0,16.0,30.0,33.6,32.4,14.1,30.0,NW,28.0,35.0,1014.1,0.0

In [21]:
good_df['Timestamp'] = pd.to_datetime(good_df[['year','month','day','hour','minute']])
good_df.head()

,year,month,day,hour,minute,Air Temp (degrees C),Apparent Temp (degrees C),Dew Pt Temp (degrees C),Humidity (%),Wind Direction,Wind Speed (km/h),Wind Gust (km/h),MSLP (hPa),Rainfall since 9 am (mm),Timestamp
0,2011,1,1.0,0.0,4.0,24.8,0.0,14.0,51.0,SE,11.0,13.0,1007.4,0.0,2011-01-01 00:04:00
1,2011,1,1.0,0.0,4.0,24.8,0.0,14.0,51.0,SE,11.0,13.0,1007.4,0.0,2011-01-01 00:04:00
2,2011,1,1.0,0.0,14.0,24.8,0.0,13.3,48.0,SE,11.0,11.0,1007.5,0.0,2011-01-01 00:14:00
3,2011,1,1.0,0.0,14.0,24.8,0.0,13.3,48.0,SE,11.0,11.0,1007.5,0.0,2011-01-01 00:14:00
4,2011,1,1.0,0.0,24.0,24.9,0.0,13.3,48.0,SE,11.0,13.0,1007.5,0.0,2011-01-01 00:24:00

In [22]:
good_df.drop(columns = ['year','month','day','hour','minute'], inplace=True)
good_df.head()

,Air Temp (degrees C),Apparent Temp (degrees C),Dew Pt Temp (degrees C),Humidity (%),Wind Direction,Wind Speed (km/h),Wind Gust (km/h),MSLP (hPa),Rainfall since 9 am (mm),Timestamp
0,24.8,0.0,14.0,51.0,SE,11.0,13.0,1007.4,0.0,2011-01-01 00:04:00
1,24.8,0.0,14.0,51.0,SE,11.0,13.0,1007.4,0.0,2011-01-01 00:04:00
2,24.8,0.0,13.3,48.0,SE,11.0,11.0,1007.5,0.0,2011-01-01 00:14:00
3,24.8,0.0,13.3,48.0,SE,11.0,11.0,1007.5,0.0,2011-01-01 00:14:00
4,24.9,0.0,13.3,48.0,SE,11.0,13.0,1007.5,0.0,2011-01-01 00:24:00

In [23]:
good_df.index = good_df['Timestamp']
good_df.drop(columns = ["Timestamp"], inplace=True)
good_df.head()

,Air Temp (degrees C),Apparent Temp (degrees C),Dew Pt Temp (degrees C),Humidity (%),Wind Direction,Wind Speed (km/h),Wind Gust (km/h),MSLP (hPa),Rainfall since 9 am (mm)
Timestamp,,,,,,,,,
2011-01-01 00:04:00,24.8,0.0,14.0,51.0,SE,11.0,13.0,1007.4,0.0
2011-01-01 00:04:00,24.8,0.0,14.0,51.0,SE,11.0,13.0,1007.4,0.0
2011-01-01 00:14:00,24.8,0.0,13.3,48.0,SE,11.0,11.0,1007.5,0.0
2011-01-01 00:14:00,24.8,0.0,13.3,48.0,SE,11.0,11.0,1007.5,0.0
2011-01-01 00:24:00,24.9,0.0,13.3,48.0,SE,11.0,13.0,1007.5,0.0

### Bad Rows DF

In [24]:
bad_df = all_df_fixed.loc[need_fix_rows]
bad_df

,year,month,day,hour,minute,Air Temp (degrees C),Apparent Temp (degrees C),Dew Pt Temp (degrees C),Humidity (%),Wind Direction,Wind Speed (km/h),Wind Gust (km/h),MSLP (hPa),Rainfall since 9 am (mm)
340282,2014\t09\t26\t17\t30\t17.6\t15.5\t15.5\t45\tEN...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
340284,2014\t09\t26\t18\t00\t17.4\t16.4\t16.4\t45\tNE...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
340285,2014\t09\t26\t18\t30\t17.4\t16.2\t16.2\t48\tN\...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
340287,2014\t09\t26\t19\t00\t16.9\t14.8\t14.8\t51\tNN...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
340288,2014\t09\t26\t19\t30\t16.4\t13.7\t13.7\t55\tN\...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
919460,2020\t11\t25\t14\t00\t28.2\t26.3\t14.1\t42\tNN...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
919461,2020\t11\t25\t14\t30\t29.6\t28.9\t15.3\t41\tNN...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
919463,2020\t11\t25\t15\t00\t29.4\t29.6\t14.8\t41\tNW...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
919464,2020\t11\t25\t15\t30\t29.8\t29.6\t14.7\t39\tNN...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
919466,2020\t11\t25\t16\t00\t27.7\t27.4\t15.4\t47\tNN...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0

In [25]:
len(bad_df) # Number of all the bad rows

632

In [26]:
no_month = np.where(all_df_fixed['month'].isna())[0].tolist() # Select rows with no data in month column
with_month = [n for n in need_fix_rows if n not in no_month] # Select rows with data clustered in month column

In [27]:
bad_w_month = all_df_fixed.loc[with_month] # Create a dataframe for bad rows with data in month column
len(bad_w_month)

16

In [28]:
bad_no_month = all_df_fixed.loc[no_month] # Create a dataframe for bad rows with NO data in month column
len(bad_no_month)

616

32+1232 = 1264 which is the exact number of row with missing values

#### Dealing with bad_df (without month)

In [29]:
bad_fixed = bad_no_month['year'].astype(str).str.split('\t', expand=True)
bad_fixed.drop(columns=[14], inplace=True)
bad_fixed.head()

          0   1   2   3   4     5     6     7   8    9  10  11      12 13
340282  2014  09  26  17  30  17.6  15.5  15.5  45  ENE  2  11  1018.1  0
340284  2014  09  26  18  00  17.4  16.4  16.4  45   NE  9  11    1018  0
340285  2014  09  26  18  30  17.4  16.2  16.2  48    N  7   9  1018.2  0
340287  2014  09  26  19  00  16.9  14.8  14.8  51  NNE  9  13  1018.6  0
340288  2014  09  26  19  30  16.4  13.7  13.7  55    N  9  13    1019  0

In [30]:
bad_fixed.columns = [
    'year', 'month', 'day', 'hour', 'minute',
    'Air Temp (degrees C)', 'Apparent Temp (degrees C)', 'Dew Pt Temp (degrees C)',
    'Humidity (%)', 'Wind Direction', 'Wind Speed (km/h)',
    'Wind Gust (km/h)', 'MSLP (hPa)', 'Rainfall since 9 am (mm)'
]

In [31]:
bad_fixed.head()

,year,month,day,hour,minute,Air Temp (degrees C),Apparent Temp (degrees C),Dew Pt Temp (degrees C),Humidity (%),Wind Direction,Wind Speed (km/h),Wind Gust (km/h),MSLP (hPa),Rainfall since 9 am (mm)
340282,2014,09,26,17,30,17.6,15.5,15.5,45,ENE,2,11,1018.1,0
340284,2014,09,26,18,00,17.4,16.4,16.4,45,NE,9,11,1018,0
340285,2014,09,26,18,30,17.4,16.2,16.2,48,N,7,9,1018.2,0
340287,2014,09,26,19,00,16.9,14.8,14.8,51,NNE,9,13,1018.6,0
340288,2014,09,26,19,30,16.4,13.7,13.7,55,N,9,13,1019,0

In [32]:
bad_fixed['Timestamp'] = pd.to_datetime(bad_fixed[['year','month','day','hour','minute']])
bad_fixed.drop(columns = ['year','month','day','hour','minute'], inplace=True)
bad_fixed.index = bad_fixed['Timestamp']
bad_fixed.drop(columns = ['Timestamp'], inplace=True)
bad_fixed.head()

,Air Temp (degrees C),Apparent Temp (degrees C),Dew Pt Temp (degrees C),Humidity (%),Wind Direction,Wind Speed (km/h),Wind Gust (km/h),MSLP (hPa),Rainfall since 9 am (mm)
Timestamp,,,,,,,,,
2014-09-26 17:30:00,17.6,15.5,15.5,45,ENE,2,11,1018.1,0
2014-09-26 18:00:00,17.4,16.4,16.4,45,NE,9,11,1018,0
2014-09-26 18:30:00,17.4,16.2,16.2,48,N,7,9,1018.2,0
2014-09-26 19:00:00,16.9,14.8,14.8,51,NNE,9,13,1018.6,0
2014-09-26 19:30:00,16.4,13.7,13.7,55,N,9,13,1019,0

#### Dealing with bad_w_month (bad with month)

In [33]:
split_bad_w_month = bad_w_month['month'].astype(str).str.split('\t', expand=True)
split_bad_w_month.head()

        0   1   2   3     4     5     6   7    8   9   10      11 12
556507   1  18  11  00  18.8  15.9   9.6  55    S  32  43  1014.8  0
556508   1  18  11  30    20  16.8  10.1  53    S  28  43  1015.1  0
556510   1  18  12  00    19  14.8  11.1  60    S  32  43  1015.4  0
556511   1  18  12  30  19.2  14.9   9.4  53  SSE  35  48  1015.6  0
556513   1  18  13  00  19.4  15.9   8.7  50    S  30  44  1015.9  0

In [34]:
year_for_bad_w_month = bad_w_month['year']
year_for_bad_w_month = pd.DataFrame(year_for_bad_w_month)
year_for_bad_w_month.head()

        year
556507  2017
556508  2017
556510  2017
556511  2017
556513  2017

In [35]:
bad_w_month_fixed = pd.merge(year_for_bad_w_month, split_bad_w_month, left_index=True, right_index=True, how='right')
bad_w_month_fixed.columns = new_names
bad_w_month_fixed.head()

,year,month,day,hour,minute,Air Temp (degrees C),Apparent Temp (degrees C),Dew Pt Temp (degrees C),Humidity (%),Wind Direction,Wind Speed (km/h),Wind Gust (km/h),MSLP (hPa),Rainfall since 9 am (mm)
556507,2017,1,18,11,00,18.8,15.9,9.6,55,S,32,43,1014.8,0
556508,2017,1,18,11,30,20,16.8,10.1,53,S,28,43,1015.1,0
556510,2017,1,18,12,00,19,14.8,11.1,60,S,32,43,1015.4,0
556511,2017,1,18,12,30,19.2,14.9,9.4,53,SSE,35,48,1015.6,0
556513,2017,1,18,13,00,19.4,15.9,8.7,50,S,30,44,1015.9,0

In [36]:
bad_w_month_fixed['Timestamp'] = pd.to_datetime(bad_w_month_fixed[['year','month','day','hour','minute']])
bad_w_month_fixed.drop(columns = ['year','month','day','hour','minute'], inplace=True)
bad_w_month_fixed.index = bad_w_month_fixed['Timestamp']
bad_w_month_fixed.drop(columns = ['Timestamp'], inplace=True)
bad_w_month_fixed.head()

,Air Temp (degrees C),Apparent Temp (degrees C),Dew Pt Temp (degrees C),Humidity (%),Wind Direction,Wind Speed (km/h),Wind Gust (km/h),MSLP (hPa),Rainfall since 9 am (mm)
Timestamp,,,,,,,,,
2017-01-18 11:00:00,18.8,15.9,9.6,55,S,32,43,1014.8,0
2017-01-18 11:30:00,20,16.8,10.1,53,S,28,43,1015.1,0
2017-01-18 12:00:00,19,14.8,11.1,60,S,32,43,1015.4,0
2017-01-18 12:30:00,19.2,14.9,9.4,53,SSE,35,48,1015.6,0
2017-01-18 13:00:00,19.4,15.9,8.7,50,S,30,44,1015.9,0

### Merge them back together

In [37]:
df_fixed = pd.concat([good_df, bad_fixed, bad_w_month_fixed])
df_fixed = df_fixed.sort_index()
df_fixed

,Air Temp (degrees C),Apparent Temp (degrees C),Dew Pt Temp (degrees C),Humidity (%),Wind Direction,Wind Speed (km/h),Wind Gust (km/h),MSLP (hPa),Rainfall since 9 am (mm)
Timestamp,,,,,,,,,
2011-01-01 00:04:00,24.8,0.0,14.0,51.0,SE,11.0,13.0,1007.4,0.0
2011-01-01 00:04:00,24.8,0.0,14.0,51.0,SE,11.0,13.0,1007.4,0.0
2011-01-01 00:14:00,24.8,0.0,13.3,48.0,SE,11.0,11.0,1007.5,0.0
2011-01-01 00:14:00,24.8,0.0,13.3,48.0,SE,11.0,11.0,1007.5,0.0
2011-01-01 00:24:00,24.9,0.0,13.3,48.0,SE,11.0,13.0,1007.5,0.0
...,...,...,...,...,...,...,...,...,...
2025-03-12 15:30:00,33.4,32.5,14.9,32.0,NW,20.0,35.0,1014.6,0.0
2025-03-12 15:34:00,33.5,32.9,14.5,31.0,NNW,26.0,41.0,1014.6,0.0
2025-03-12 16:00:00,34.4,34.2,14.8,30.0,WNW,26.0,41.0,1014.4,0.0
2025-03-12 16:30:00,33.6,32.4,14.1,30.0,NW,28.0,35.0,1014.1,0.0
2025-03-12 16:30:00,33.6,32.4,14.1,30.0,WNW,26.0,41.0,1014.1,0.0

In [38]:
print(df_fixed.isna().values.any())

False

#### Right here, all the data are in the same format (timestamp, Air Temp, Apparent Temp, Dew Pt Temp, ....) but this doesn't mean that the data is all clean.
There might be some duplicate, missing time period, error values (outliers), etc.
We still ned to check for those and try to fix them.

## Deal with Duplicated Rows (after cleaning)

In [39]:
df_fixed['Air Temp (degrees C)'] = pd.to_numeric(df_fixed['Air Temp (degrees C)'], errors='coerce')
df_fixed['Apparent Temp (degrees C)'] = pd.to_numeric(df_fixed['Apparent Temp (degrees C)'], errors='coerce')
df_fixed['Dew Pt Temp (degrees C)'] = pd.to_numeric(df_fixed['Dew Pt Temp (degrees C)'], errors='coerce')
df_fixed['Humidity (%)'] = pd.to_numeric(df_fixed['Humidity (%)'], errors='coerce')
df_fixed['Wind Direction'] = df_fixed['Wind Direction'].astype(str)
df_fixed['Wind Direction'] = df_fixed['Wind Direction'].str.strip()
df_fixed['Wind Speed (km/h)'] = pd.to_numeric(df_fixed['Wind Speed (km/h)'], errors='coerce')
df_fixed['Wind Gust (km/h)'] = pd.to_numeric(df_fixed['Wind Gust (km/h)'], errors='coerce')
df_fixed['MSLP (hPa)'] = pd.to_numeric(df_fixed['MSLP (hPa)'], errors='coerce')
df_fixed['Rainfall since 9 am (mm)'] = pd.to_numeric(df_fixed['Rainfall since 9 am (mm)'], errors='coerce')
df_fixed.tail()

,Air Temp (degrees C),Apparent Temp (degrees C),Dew Pt Temp (degrees C),Humidity (%),Wind Direction,Wind Speed (km/h),Wind Gust (km/h),MSLP (hPa),Rainfall since 9 am (mm)
Timestamp,,,,,,,,,
2025-03-12 15:30:00,33.4,32.5,14.9,32.0,NW,20.0,35.0,1014.6,0.0
2025-03-12 15:34:00,33.5,32.9,14.5,31.0,NNW,26.0,41.0,1014.6,0.0
2025-03-12 16:00:00,34.4,34.2,14.8,30.0,WNW,26.0,41.0,1014.4,0.0
2025-03-12 16:30:00,33.6,32.4,14.1,30.0,NW,28.0,35.0,1014.1,0.0
2025-03-12 16:30:00,33.6,32.4,14.1,30.0,WNW,26.0,41.0,1014.1,0.0

In [40]:
print(df_fixed.duplicated().sum())

511093

In [41]:
df_fixed = df_fixed.drop_duplicates()
df_fixed.tail()

,Air Temp (degrees C),Apparent Temp (degrees C),Dew Pt Temp (degrees C),Humidity (%),Wind Direction,Wind Speed (km/h),Wind Gust (km/h),MSLP (hPa),Rainfall since 9 am (mm)
Timestamp,,,,,,,,,
2025-03-12 15:30:00,33.4,32.5,14.9,32.0,NW,20.0,35.0,1014.6,0.0
2025-03-12 15:34:00,33.5,32.9,14.5,31.0,NNW,26.0,41.0,1014.6,0.0
2025-03-12 16:00:00,34.4,34.2,14.8,30.0,WNW,26.0,41.0,1014.4,0.0
2025-03-12 16:30:00,33.6,32.4,14.1,30.0,NW,28.0,35.0,1014.1,0.0
2025-03-12 16:30:00,33.6,32.4,14.1,30.0,WNW,26.0,41.0,1014.1,0.0

In [42]:
print(df_fixed.duplicated().sum())

0

## Deal with Missing Value

In [43]:
df_fixed.describe()

,Air Temp (degrees C),Apparent Temp (degrees C),Dew Pt Temp (degrees C),Humidity (%),Wind Speed (km/h),Wind Gust (km/h),MSLP (hPa),Rainfall since 9 am (mm)
count,574867.000000,574867.000000,574867.000000,574867.000000,574867.000000,574867.000000,574867.000000,574867.000000
mean,15.897796,12.252478,9.093960,66.845907,19.208612,22.606132,1016.433951,0.791475
std,5.599044,14.981336,4.062121,17.708794,34.041390,43.707640,85.742763,2.976234
min,0.500000,-9999.000000,-9.600000,0.000000,-9999.000000,-9999.000000,-9999.000000,0.000000
25%,11.900000,7.800000,6.100000,55.000000,11.000000,13.000000,1012.200000,0.000000
50%,15.200000,11.900000,8.700000,68.000000,17.000000,20.000000,1017.300000,0.000000
75%,19.100000,16.700000,11.700000,80.000000,26.000000,30.000000,1022.400000,0.200000
max,43.500000,43.300000,36.900000,100.000000,100.000000,109.000000,1041.900000,54.600000

So, there are missing values (which are in the form of -9999) in
1. Apparent Temp (degrees C)
2. Wind Speed (km/h)
3. Wind Gust (km/h)
4. MSLP (hPa)

and also missing value in Wind Direction (in form of '-')

5. Wind Direction

In [47]:
cols = [
    'Apparent Temp (degrees C)',
    'Wind Speed (km/h)',
    'Wind Gust (km/h)',
    'MSLP (hPa)'
]

df_fixed[df_fixed[cols].isin([-9999]).any(axis=1)]

,Air Temp (degrees C),Apparent Temp (degrees C),Dew Pt Temp (degrees C),Humidity (%),Wind Direction,Wind Speed (km/h),Wind Gust (km/h),MSLP (hPa),Rainfall since 9 am (mm)
Timestamp,,,,,,,,,
2021-03-03 11:00:00,16.1,12.8,6.5,53.0,-,-9999.0,-9999.0,1020.8,0.0
2021-03-03 15:00:00,17.3,14.3,7.9,54.0,S,28.0,-9999.0,1019.8,0.0
2021-05-30 10:00:00,5.7,2.5,3.2,84.0,WNW,6.0,9.0,-9999.0,0.0
2021-05-30 10:30:00,8.2,5.9,4.8,79.0,NNE,4.0,9.0,-9999.0,0.0
2021-05-30 11:00:00,10.3,8.8,5.1,70.0,SE,4.0,9.0,-9999.0,0.0
2021-05-30 11:30:00,11.5,10.0,5.2,65.0,SE,2.0,9.0,-9999.0,0.0
2021-05-30 12:00:00,11.4,9.4,4.2,61.0,ENE,2.0,7.0,-9999.0,0.0
2021-05-30 12:30:00,12.4,11.1,4.1,57.0,ENE,6.0,11.0,-9999.0,0.0
2021-05-30 13:00:00,12.1,10.0,3.9,57.0,SE,9.0,11.0,-9999.0,0.0
2021-05-30 13:30:00,12.7,10.4,4.7,58.0,ESE,9.0,13.0,-9999.0,0.0
2021-05-30 14:00:00,13.0,10.4,4.2,55.0,SSE,7.0,11.0,-9999.0,0.0
2021-05-30 14:30:00,13.1,11.3,3.7,53.0,ESE,4.0,11.0,-9999.0,0.0
2021-05-30 15:00:00,14.1,11.9,3.3,48.0,ESE,4.0,9.0,-9999.0,0.0
2021-05-30 15:30:00,13.2,11.1,5.6,60.0,SE,2.0,9.0,-9999.0,0.0
2021-05-30 16:00:00,12.9,10.8,5.6,61.0,ESE,7.0,9.0,-9999.0,0.0
2021-05-30 16:30:00,12.4,10.3,5.8,64.0,CALM,0.0,0.0,-9999.0,0.0
2021-05-30 17:00:00,10.7,9.8,5.9,72.0,CALM,0.0,0.0,-9999.0,0.0
2021-05-30 17:30:00,9.1,8.1,5.8,80.0,CALM,0.0,0.0,-9999.0,0.0
2021-07-14 15:30:00,13.5,9.2,9.4,76.0,N,32.0,43.0,-9999.0,0.2
2021-08-31 08:00:00,13.3,8.3,4.5,55.0,N,52.0,63.0,-9999.0,0.0
2021-08-31 08:30:00,13.4,8.6,4.6,55.0,NNE,52.0,70.0,-9999.0,0.0
2021-08-31 09:00:00,13.5,9.0,4.1,53.0,NNE,46.0,65.0,-9999.0,0.0
2021-08-31 09:30:00,13.4,8.6,4.6,55.0,NNE,48.0,59.0,-9999.0,0.0
2023-01-19 14:00:00,17.1,13.7,7.5,53.0,-,-9999.0,-9999.0,1017.2,0.0
2023-03-03 10:30:00,17.4,14.4,7.7,53.0,-,-9999.0,-9999.0,1019.2,0.0
2023-03-04 06:00:00,14.2,13.5,11.9,86.0,N,9.0,11.0,-9999.0,0.0
2023-03-23 10:30:00,16.9,16.8,15.9,94.0,N,22.0,-9999.0,1016.3,1.4
2023-05-02 16:30:00,19.8,16.5,6.2,41.0,W,28.0,-9999.0,1012.3,0.0
2023-06-23 04:00:00,9.2,5.9,6.5,83.0,NNE,20.0,28.0,-9999.0,2.8
2023-08-23 19:00:00,14.4,11.0,6.0,57.0,NNW,15.0,19.0,-9999.0,0.0
2023-09-18 13:30:00,16.3,15.0,11.2,72.0,-,-9999.0,-9999.0,1014.4,0.0
2023-12-23 15:00:00,21.5,18.9,12.1,55.0,SSW,19.0,32.0,-9999.0,0.0
2024-02-21 13:30:00,31.8,30.0,14.4,34.0,N,32.0,44.0,-9999.0,0.0
2024-04-04 15:00:00,17.7,14.6,7.4,51.0,S,26.0,-9999.0,1025.9,0.0
2024-04-07 02:30:00,17.0,18.5,14.6,86.0,SSW,9.0,11.0,-9999.0,0.0
2024-04-15 08:30:00,13.1,11.8,9.2,77.0,N,15.0,17.0,-9999.0,0.0
2024-04-15 09:00:00,14.9,13.8,9.9,72.0,N,11.0,13.0,-9999.0,0.0
2024-04-15 09:30:00,15.7,14.6,9.8,68.0,N,11.0,13.0,-9999.0,0.0
2024-04-15 10:00:00,17.1,16.4,10.2,64.0,NNW,6.0,9.0,-9999.0,0.0
2024-04-15 10:30:00,17.8,16.6,10.4,62.0,W,9.0,11.0,-9999.0,0.0
2024-04-15 11:00:00,18.5,17.5,10.3,59.0,WNW,4.0,11.0,-9999.0,0.0
2024-10-10 20:00:00,13.5,10.5,5.9,60.0,S,15.0,22.0,-9999.0,0.0
2024-10-15 11:30:00,21.7,19.7,10.2,48.0,-,-9999.0,-9999.0,1020.2,0.0
2024-10-15 13:30:00,25.0,23.7,11.2,42.0,-,-9999.0,-9999.0,1018.2,0.0
2024-11-22 02:00:00,15.9,-9999.0,15.9,100.0,NNE,13.0,17.0,1020.3,0.0

In [50]:
df_fixed[df_fixed['Wind Direction'].isin(['-'])]

,Air Temp (degrees C),Apparent Temp (degrees C),Dew Pt Temp (degrees C),Humidity (%),Wind Direction,Wind Speed (km/h),Wind Gust (km/h),MSLP (hPa),Rainfall since 9 am (mm)
Timestamp,,,,,,,,,
2021-03-03 11:00:00,16.1,12.8,6.5,53.0,-,-9999.0,-9999.0,1020.8,0.0
2023-01-19 14:00:00,17.1,13.7,7.5,53.0,-,-9999.0,-9999.0,1017.2,0.0
2023-03-03 10:30:00,17.4,14.4,7.7,53.0,-,-9999.0,-9999.0,1019.2,0.0
2023-09-18 13:30:00,16.3,15.0,11.2,72.0,-,-9999.0,-9999.0,1014.4,0.0
2024-10-15 11:30:00,21.7,19.7,10.2,48.0,-,-9999.0,-9999.0,1020.2,0.0
2024-10-15 13:30:00,25.0,23.7,11.2,42.0,-,-9999.0,-9999.0,1018.2,0.0

### No more weird stuff!!!

All the data is quite clean now, but still so much more to do.
1. Convert wind direction into xy-direction
2. Unify timestamp

#### I think we should just download df_fixed into csv and use this csv to work on other notebook instead (so we don't have to mess with these data cleaning anymore).

In [44]:
# df_fixed.to_csv('cleaned_Melbourne01.csv')